services:
  - type: web
    name: kitrade-preview
    runtime: static
    repo: https://github.com/polygalovartur22-create/kitrade-preview
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: KITRADE_BUILD_MODE
        value: preview
    headers:
      - path: "/*"
        name: X-Robots-Tag
        value: noindex, nofollow, noarchive
    routes:
      - type: redirect
        source: /catalog/product/dvigatel-v-sbore-weichai-wp12-430e50-1001/
        destination: /catalog/product/dvigatel-v-sbore-weichai-1001/
      - type: redirect
        source: /catalog/product/dvigatel-wd615-47-evro-2-1002/
        destination: /catalog/product/dvigatel-evro-2-1002/
      - type: redirect
        source: /catalog/product/dvigatel-v-sbore-eicha-analog-weichai-wp12-430e50-1003/
        destination: /catalog/product/dvigatel-v-sbore-eicha-analog-weichai-1003/
      - type: redirect
        source: /catalog/product/silovoi-kabel-voyah-h56a9325010aa-1528/
        destination: /catalog/product/silovoi-kabel-voyah-1528/
      - type: redirect
        source: /catalog/product/steklo-bmw-x5li-art-51375a44964-1594/
        destination: /catalog/product/steklo-bmw-x5li-1594/
      - type: redirect
        source: /catalog/product/steklo-bmw-x5li-art-51359854340-1612/
        destination: /catalog/product/steklo-bmw-x5li-1612/
      - type: redirect
        source: /catalog/product/steklo-bmw-x5li-art-51359854428-1642/
        destination: /catalog/product/steklo-bmw-x5li-1642/
      - type: redirect
        source: /catalog/product/podshipnik-62-34-rs1-1684/
        destination: /catalog/product/podshipnik-1684/
      - type: redirect
        source: /catalog/product/dvigatel-kr15-ddt-e-power-gibrid-1701/
        destination: /catalog/product/dvigatel-ddt-e-power-gibrid-1701/
      - type: redirect
        source: /catalog/product/novyi-dvigatel-v-sbore-kr15-ddt-1703/
        destination: /catalog/product/novyi-dvigatel-v-sbore-1703/
      - type: redirect
        source: /catalog/product/dvigatel-original-kr15-ddt-e-power-gibrid-1704/
        destination: /catalog/product/dvigatel-original-e-power-gibrid-1704/
      - type: redirect
        source: /catalog/product/dvigatel-v-sbore-kr15-ddt-original-1707/
        destination: /catalog/product/dvigatel-v-sbore-original-1707/
      - type: redirect
        source: /catalog/product/dvigatel-v-sbore-geely-coolray-jlh3g15td-1708/
        destination: /catalog/product/dvigatel-v-sbore-geely-coolray-1708/
      - type: redirect
        source: /catalog/product/dvigatel-v-sbore-geely-coolray-jlh3g15td-1709/
        destination: /catalog/product/dvigatel-v-sbore-geely-coolray-1709/
      - type: redirect
        source: /catalog/product/podshipnik-63-33ya1-rs1-1747/
        destination: /catalog/product/podshipnik-1747/
